export const ICON_NAME_LIST = [
  'google-logo',
  'recipe',
  'calendar',
  'home',
  'camera',
  'check-mark',
  'list-check',
  'arrow-back',
  'filled-close',
  'alert',
  'warning',
  'info-circle',
  'bell',
] as const;
