export const ICON_NAME_LIST = [
  'google-logo',
  'recipe',
  'calendar',
  'home',
  'camera',
  'check-mark',
  'list-check',
  'arrow-back',
  'filled-close',
  'alert',
  'warning',
  'info-circle',
  'bell',
  'pencil',
  'new-window-arrow',
  'close-circle',
  'emoji-sad',
  'list',
  'bookmark',
  'bookmark-outline',
  'search',
  'add',
  'close',
  'window-open',
  'copy',
  'reload',
] as const;
